### ISSUE TITLE
Ajouter les catégories dans le profil

### ISSUE THREAD

**Issue by arthaud-proust** [arthaud-proust/dev.arthaud.dressing#5]
Emma remonte que les catégories sont personnelles, elle pourrait être dans le profil

**Comment by EmmaGuillaume** [comment]
super xp, je recommande 5/5

**Comment by EmmaGuillaume** [comment]
par contre bon, c'est pas aussi marrant que next avec les routes mais bon, je suis tolérante quoi

**Comment by EmmaGuillaume** [comment]
Pas besoin de se justifier hein

**Comment by arthaud-proust** [comment]
Alors déjà installe PhpStorm tu verras 🤓
